# Generated by Django 4.2.28 on 2026-03-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GhanaPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('ascii_name', models.CharField(db_index=True, max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('feature_code', models.CharField(blank=True, max_length=10)),
                ('population', models.IntegerField(default=0)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(default='geonames', max_length=20)),
            ],
        ),
        migrations.RenameIndex(
            model_name='scantile',
            new_name='scanning_sc_priorit_b36024_idx',
            old_name='scanning_ti_priorit_idx',
        ),
        migrations.AlterField(
            model_name='autoscanconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='ghanaplace',
            index=models.Index(fields=['name'], name='scanning_gh_name_dbd94d_idx'),
        ),
        migrations.AddIndex(
            model_name='ghanaplace',
            index=models.Index(fields=['ascii_name'], name='scanning_gh_ascii_n_433957_idx'),
        ),
    ]
