# Generated by Django 4.2.28 on 2026-04-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0004_ghanaplace_feature_code_wider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ghanaplace',
            name='source',
            field=models.CharField(default='geonames', max_length=20),
        ),
    ]
