# Generated by Django 6.0.2 on 2026-02-18 15:54

import django.contrib.gis.db.models.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('validating', 'Validating'), ('exporting', 'Exporting'), ('preprocessing', 'Preprocessing'), ('inferring', 'Inferring'), ('postprocessing', 'Postprocessing'), ('storing', 'Storing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='queued', max_length=20)),
                ('aoi_geometry', django.contrib.gis.db.models.fields.PolygonField(help_text='Area of Interest geometry', srid=4326)),
                ('aoi_hash', models.CharField(db_index=True, help_text='Deterministic hash of AOI for deduplication', max_length=64)),
                ('start_date', models.DateField(help_text='Start date for imagery analysis')),
                ('end_date', models.DateField(help_text='End date for imagery analysis')),
                ('model_version', models.CharField(help_text='ML model version used', max_length=50)),
                ('preprocessing_version', models.CharField(help_text='Preprocessing version', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'indexes': [models.Index(fields=['status'], name='jobs_job_status_7d017a_idx'), models.Index(fields=['created_at'], name='jobs_job_created_1b3a4d_idx'), models.Index(fields=['aoi_hash'], name='jobs_job_aoi_has_f362d9_idx')],
            },
        ),
    ]
