# Generated by Django 4.2.28 on 2026-03-30 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_add_organisation_to_job'),
        ('jobs', '0006_job_patch_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='organisation',
            field=models.ForeignKey(blank=True, help_text='Organisation that owns this job. Null for automated scans (visible to all orgs).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='accounts.organisation'),
        ),
    ]
