# Generated by Django 4.2.28 on 2026-02-19 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('analyst', 'Analyst'), ('inspector', 'Inspector'), ('viewer', 'Viewer')], default='viewer', max_length=20)),
                ('organization', models.CharField(choices=[('epa', 'Environmental Protection Agency'), ('minerals_commission', 'Minerals Commission'), ('cersgis', 'CERSGIS'), ('forestry_commission', 'Forestry Commission'), ('other', 'Other')], default='other', max_length=30)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('receive_email_alerts', models.BooleanField(default=True)),
                ('receive_sms_alerts', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
