# Generated by Django 4.2.28 on 2026-03-04 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_sla_evidencephoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto (System)')], default='light', max_length=10)),
                ('layout', models.CharField(choices=[('compact', 'Compact'), ('spaced', 'Spaced'), ('comfortable', 'Comfortable')], default='comfortable', max_length=15)),
                ('font_size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('extra_large', 'Extra Large')], default='medium', max_length=15)),
                ('high_contrast', models.BooleanField(default=False)),
                ('show_alerts_widget', models.BooleanField(default=True)),
                ('show_assignments_widget', models.BooleanField(default=True)),
                ('show_reports_widget', models.BooleanField(default=True)),
                ('show_audit_widget', models.BooleanField(default=True)),
                ('default_page', models.CharField(choices=[('home', 'Home'), ('alerts', 'Alerts'), ('inspector', 'Inspector'), ('report', 'Report')], default='home', max_length=20)),
                ('email_notifications', models.BooleanField(default=True)),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(default='22:00')),
                ('quiet_hours_end', models.TimeField(default='08:00')),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('language', models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('es', 'Spanish')], default='en', max_length=5)),
                ('critical_alerts_override', models.BooleanField(default=True)),
                ('activity_visibility', models.BooleanField(default=True)),
                ('location_sharing', models.BooleanField(default=False)),
                ('mobile_push_notifications', models.BooleanField(default=True)),
                ('mobile_offline_sync', models.BooleanField(default=True)),
                ('mobile_theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto (System)')], default='auto', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Preferences',
                'verbose_name_plural': 'User Preferences',
            },
        ),
    ]
