# Generated by Django 4.2.28 on 2026-03-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_systemconfig_org_overrides'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
