# Generated by Django 4.2.28 on 2026-04-05 13:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_assignment_protect_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='max_pending_override',
            field=models.IntegerField(blank=True, help_text='Override the system-wide max pending assignments for inspectors in this organisation. Leave blank to use the system default.', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='sla_days_override',
            field=models.IntegerField(blank=True, help_text='Override the system-wide SLA days for inspectors in this organisation. Leave blank to use the system default.', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
