# Generated by Django 4.2.28 on 2026-04-05 13:37

import apps.notifications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationinbox',
            name='link',
            field=models.CharField(blank=True, max_length=300, validators=[apps.notifications.models._validate_notification_link]),
        ),
    ]
