# Generated by Django 4.2.28 on 2026-02-19 16:39

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0002_alter_job_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('new_detection', 'New Detection'), ('expansion_detected', 'Site Expansion Detected'), ('recurring_site', 'Recurring Illegal Site'), ('high_confidence', 'High Confidence Detection')], db_index=True, default='new_detection', max_length=25)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('dispatched', 'Inspector Dispatched'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], db_index=True, default='open', max_length=15)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DetectedSite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(help_text='Detection polygon in WGS-84', srid=4326)),
                ('centroid', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Centroid of detection polygon — auto-computed', null=True, srid=4326)),
                ('confidence_score', models.FloatField(help_text='Mean probability score within this polygon', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('area_hectares', models.FloatField(help_text='Area of detection polygon in hectares', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('detection_date', models.DateField(db_index=True, help_text='Date the imagery used for this detection was acquired')),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('confirmed_illegal', 'Confirmed Illegal'), ('confirmed_legal', 'Confirmed Legal'), ('false_positive', 'False Positive'), ('dismissed', 'Dismissed')], db_index=True, default='pending_review', max_length=25)),
                ('legal_status', models.CharField(choices=[('illegal', 'Illegal'), ('legal', 'Legal'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=10)),
                ('concession_overlap_pct', models.FloatField(blank=True, help_text='Percentage of detection polygon within a concession boundary', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('first_detected_at', models.DateField(blank=True, help_text='Date this location was first ever detected', null=True)),
                ('recurrence_count', models.PositiveIntegerField(default=1, help_text='How many times this location has been flagged (>=2 means recurring)')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Detected Site',
                'verbose_name_plural': 'Detected Sites',
                'ordering': ['-detection_date', '-confidence_score'],
            },
        ),
        migrations.CreateModel(
            name='SatelliteImagery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scene_id', models.CharField(db_index=True, help_text='HLS tile identifier e.g. HLS.S30.T30NXM.2024001T100000', max_length=255, unique=True)),
                ('satellite', models.CharField(choices=[('L8', 'Landsat 8'), ('L9', 'Landsat 9'), ('S2A', 'Sentinel-2A'), ('S2B', 'Sentinel-2B')], db_index=True, max_length=5)),
                ('acquisition_date', models.DateField(db_index=True)),
                ('cloud_cover_pct', models.FloatField(help_text='Cloud cover percentage for this scene', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('bands_processed', models.JSONField(default=list, help_text='List of band names processed for this scene')),
                ('preprocessing_version', models.CharField(help_text='Version of preprocessing pipeline used', max_length=50)),
                ('coverage_geometry', django.contrib.gis.db.models.fields.PolygonField(help_text='Spatial extent / tile boundary of this scene', srid=4326)),
                ('gcs_path', models.CharField(blank=True, help_text='GCS path to the exported GeoTIFF e.g. gs://bucket/path/file.tif', max_length=500)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Satellite Imagery',
                'verbose_name_plural': 'Satellite Imagery',
                'ordering': ['-acquisition_date'],
                'indexes': [models.Index(fields=['scene_id'], name='detections__scene_i_ca5b1b_idx'), models.Index(fields=['acquisition_date'], name='detections__acquisi_82dfdc_idx'), models.Index(fields=['satellite'], name='detections__satelli_fad1ca_idx')],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('region_type', models.CharField(choices=[('protected_forest', 'Protected Forest'), ('legal_concession_area', 'Legal Concession Area'), ('hotspot', 'Known Hotspot'), ('water_body', 'Water Body'), ('buffer_zone', 'Buffer Zone'), ('district', 'District')], db_index=True, max_length=30)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(help_text='Boundary polygon(s) for this region', srid=4326)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_inspectors', models.ManyToManyField(blank=True, related_name='assigned_regions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ModelRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_name', models.CharField(help_text='Human-readable model name e.g. FPN-ResNet50-6band', max_length=100)),
                ('model_version', models.CharField(db_index=True, help_text='Version tag e.g. v1.0, best_precision', max_length=50)),
                ('checkpoint_path', models.CharField(help_text='Local or GCS path to the .pth checkpoint file', max_length=500)),
                ('architecture', models.CharField(default='FPN', help_text='Model architecture e.g. FPN, UNet, SegFormer', max_length=100)),
                ('encoder', models.CharField(default='resnet50', help_text='Encoder backbone e.g. resnet50', max_length=100)),
                ('bands_used', models.JSONField(default=list, help_text='Ordered list of band names used as input')),
                ('val_precision', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('val_recall', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('val_iou', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('val_f1', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('inference_threshold', models.FloatField(default=0.5, help_text='Probability threshold used during this run', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('run_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_runs', to='jobs.job')),
            ],
            options={
                'verbose_name': 'Model Run',
                'verbose_name_plural': 'Model Runs',
                'ordering': ['-run_at'],
            },
        ),
        migrations.CreateModel(
            name='LegalConcession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('license_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('concession_name', models.CharField(max_length=255)),
                ('holder_name', models.CharField(help_text='License holder / company name', max_length=255)),
                ('license_type', models.CharField(choices=[('large_scale', 'Large Scale'), ('small_scale', 'Small Scale'), ('exploration', 'Exploration'), ('reconnaissance', 'Reconnaissance')], db_index=True, max_length=20)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(help_text='Concession boundary polygon(s)', srid=4326)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether the license is currently valid')),
                ('district', models.CharField(blank=True, max_length=100)),
                ('data_source', models.CharField(choices=[('minerals_commission', 'Minerals Commission'), ('cersgis', 'CERSGIS'), ('epa', 'Environmental Protection Agency')], default='minerals_commission', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concessions', to='detections.region')),
            ],
            options={
                'verbose_name': 'Legal Concession',
                'verbose_name_plural': 'Legal Concessions',
                'ordering': ['concession_name'],
            },
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visit_date', models.DateField(db_index=True)),
                ('gps_coordinates', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='GPS location where inspector stood during visit', null=True, srid=4326)),
                ('outcome', models.CharField(blank=True, choices=[('confirmed_illegal', 'Confirmed Illegal Mining'), ('confirmed_legal', 'Confirmed Legal Activity'), ('false_positive', 'False Positive — No Mining'), ('inconclusive', 'Inconclusive')], db_index=True, max_length=25, null=True)),
                ('field_notes', models.TextField(blank=True)),
                ('evidence_photos', models.JSONField(default=list, help_text='List of GCS paths or media paths to evidence photos')),
                ('drone_footage_path', models.CharField(blank=True, help_text='GCS path to drone footage from this visit', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='detections.alert')),
                ('detected_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='detections.detectedsite')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inspection',
                'verbose_name_plural': 'Inspections',
                'ordering': ['-visit_date'],
            },
        ),
        migrations.AddField(
            model_name='detectedsite',
            name='intersecting_concession',
            field=models.ForeignKey(blank=True, help_text='Concession this site overlaps, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detections', to='detections.legalconcession'),
        ),
        migrations.AddField(
            model_name='detectedsite',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detected_sites', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='detectedsite',
            name='model_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detected_sites', to='detections.modelrun'),
        ),
        migrations.AddField(
            model_name='detectedsite',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detections', to='detections.region'),
        ),
        migrations.AddField(
            model_name='detectedsite',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_sites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detectedsite',
            name='satellite_imagery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detected_sites', to='detections.satelliteimagery'),
        ),
        migrations.AddField(
            model_name='alert',
            name='detected_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='detections.detectedsite'),
        ),
        migrations.CreateModel(
            name='SiteTimelapse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveSmallIntegerField(db_index=True, help_text='Year this composite represents')),
                ('acquisition_period', models.CharField(help_text='Period label e.g. "2020-Q1" or "2020"', max_length=20)),
                ('thumbnail_url', models.URLField(blank=True, help_text='Public URL to the RGB thumbnail image', max_length=1000)),
                ('gcs_path', models.CharField(blank=True, help_text='GCS path to the full-resolution GeoTIFF for this year', max_length=500)),
                ('cloud_cover_pct', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('mean_ndvi', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-1.0), django.core.validators.MaxValueValidator(1.0)])),
                ('mean_bsi', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-1.0), django.core.validators.MaxValueValidator(1.0)])),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('detected_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timelapse_frames', to='detections.detectedsite')),
            ],
            options={
                'verbose_name': 'Site Timelapse Frame',
                'verbose_name_plural': 'Site Timelapse Frames',
                'ordering': ['detected_site', 'year'],
                'indexes': [models.Index(fields=['year'], name='detections__year_917fb8_idx')],
                'unique_together': {('detected_site', 'year')},
            },
        ),
        migrations.AddIndex(
            model_name='region',
            index=models.Index(fields=['region_type'], name='detections__region__19a43f_idx'),
        ),
        migrations.AddIndex(
            model_name='region',
            index=models.Index(fields=['is_active'], name='detections__is_acti_69c9b0_idx'),
        ),
        migrations.AddIndex(
            model_name='modelrun',
            index=models.Index(fields=['model_version'], name='detections__model_v_40a32d_idx'),
        ),
        migrations.AddIndex(
            model_name='modelrun',
            index=models.Index(fields=['run_at'], name='detections__run_at_bc92b3_idx'),
        ),
        migrations.AddIndex(
            model_name='legalconcession',
            index=models.Index(fields=['license_number'], name='detections__license_b12a1b_idx'),
        ),
        migrations.AddIndex(
            model_name='legalconcession',
            index=models.Index(fields=['is_active'], name='detections__is_acti_ef2883_idx'),
        ),
        migrations.AddIndex(
            model_name='legalconcession',
            index=models.Index(fields=['license_type'], name='detections__license_c031ca_idx'),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['visit_date'], name='detections__visit_d_b1e9d9_idx'),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['outcome'], name='detections__outcome_eccd3a_idx'),
        ),
        migrations.AddIndex(
            model_name='detectedsite',
            index=models.Index(fields=['status'], name='detections__status_2b15a9_idx'),
        ),
        migrations.AddIndex(
            model_name='detectedsite',
            index=models.Index(fields=['legal_status'], name='detections__legal_s_6aa15d_idx'),
        ),
        migrations.AddIndex(
            model_name='detectedsite',
            index=models.Index(fields=['detection_date'], name='detections__detecti_573f57_idx'),
        ),
        migrations.AddIndex(
            model_name='detectedsite',
            index=models.Index(fields=['confidence_score'], name='detections__confide_20aa2c_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['status'], name='detections__status_bdc9f2_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['severity'], name='detections__severit_263515_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['created_at'], name='detections__created_e25360_idx'),
        ),
    ]
