# Generated by Django 4.2.28 on 2026-02-23 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='region',
            name='detections__region__19a43f_idx',
        ),
        migrations.RemoveIndex(
            model_name='region',
            name='detections__is_acti_69c9b0_idx',
        ),
    ]
