# Generated by Django 4.2.28 on 2026-03-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0005_detectedsite_patch_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='region_type',
            field=models.CharField(choices=[('protected_forest', 'Protected Forest'), ('legal_concession_area', 'Legal Concession Area'), ('hotspot', 'Known Hotspot'), ('water_body', 'Water Body'), ('buffer_zone', 'Buffer Zone'), ('district', 'District'), ('admin_district', 'Administrative District')], db_index=True, max_length=30),
        ),
    ]
