# Generated by Django 4.2.28 on 2026-03-25 09:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_job_patch_images'),
        ('detections', '0006_add_admin_district_region_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('occurrence_number', models.PositiveIntegerField(help_text='1 = first detection, 2 = first recurrence, etc.')),
                ('detection_date', models.DateField()),
                ('confidence_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('area_hectares', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('img_false_color', models.CharField(blank=True, default='', max_length=500)),
                ('img_prediction_mask', models.CharField(blank=True, default='', max_length=500)),
                ('img_probability_heatmap', models.CharField(blank=True, default='', max_length=500)),
                ('img_overlay', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detection_snapshots', to='jobs.job')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='detections.detectedsite')),
            ],
            options={
                'verbose_name': 'Detection Snapshot',
                'verbose_name_plural': 'Detection Snapshots',
                'ordering': ['occurrence_number'],
                'unique_together': {('site', 'occurrence_number')},
            },
        ),
    ]
