"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from decouple import config
import platform


BASE_DIR = Path(__file__).resolve().parent.parent

# Environment configuration
ENVIRONMENT = config('ENVIRONMENT', default='Development')
DJANGO_ENVIRONMENT = config('DJANGO_ENVIRONMENT', default='development')


SECRET_KEY = config('SECRET_KEY')  # Must be set in .env — no insecure fallback
DEBUG = config('DEBUG', default=False, cast=bool)
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1,0.0.0.0', cast=lambda v: [s.strip() for s in v.split(',')])

# CSRF trusted origins for browser preview
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'http://127.0.0.1:62075',
    'http://localhost:62075',
    'http://localhost:8001',
    'http://127.0.0.1:8001',
    'http://34.26.32.215',
]

# Additional CORS settings for development
CORS_ALLOW_ALL_ORIGINS = DEBUG
CORS_ALLOW_CREDENTIALS = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
    'corsheaders',
    'rest_framework',
    # Custom apps
    'apps.dashboard',
    'analysis',
    'uploads',
    # HLS Pipeline apps
    'apps.jobs',
    'apps.gee',
    'apps.preprocessing',
    'apps.inference',
    'apps.postprocessing',
    'apps.results',
    'apps.core',
    'apps.scanning',
    # Domain models
    'apps.accounts',
    'apps.detections',
    'apps.api',
    'apps.notifications',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'apps.dashboard.middleware.RoleBasedAccessMiddleware',
    'csp.middleware.CSPMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'config.context_processors.app_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


if platform.system() == 'Windows':
    # Override via .env to avoid hardcoding one machine's QGIS install path.
    # Defaults keep existing behaviour when the env vars are not set.
    _gdal = config('GDAL_LIBRARY_PATH', default=r'C:\Program Files\QGIS 3.44.7\bin\gdal312.dll')
    _geos = config('GEOS_LIBRARY_PATH', default=r'C:\Program Files\QGIS 3.44.7\bin\geos_c.dll')
    _proj = config('PROJ_LIB',          default=r'C:\Program Files\QGIS 3.44.7\share\proj')
    if _gdal: GDAL_LIBRARY_PATH = _gdal
    if _geos: GEOS_LIBRARY_PATH = _geos
    if _proj:
        os.environ['PROJ_LIB']  = _proj   # PROJ < 9
        os.environ['PROJ_DATA'] = _proj   # PROJ >= 9 (QGIS 3.x uses PROJ 9)

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': config('DB_NAME', default='galamsey_watch_db'),
        'USER': config('DB_USER', default='admin'),
        'PASSWORD': config('DB_PASSWORD', default=''),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5433'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Accra'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Security Settings
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_HSTS_SECONDS = 31536000 if not DEBUG else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = True if not DEBUG else False
SECURE_HSTS_PRELOAD = True if not DEBUG else False

# Session Security
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True

# ── Session Timeout ──────────────────────────────────────────
# Sessions die when the browser is closed (no "remember me" cookie).
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
# Absolute ceiling: even an active session expires after 4 hours.
SESSION_COOKIE_AGE = 4 * 60 * 60          # 4 hours in seconds
# Sliding expiry: any request resets the 8-hour clock.
SESSION_SAVE_EVERY_REQUEST = True
# Frontend idle timeout fed to the JS timer (seconds).
# JS shows a 5-minute warning, then logs out.
SESSION_IDLE_TIMEOUT = 30 * 60            # 30 minutes

# Content Security Policy (enforced by csp.middleware.CSPMiddleware).
# unsafe-inline is retained while inline scripts/styles are still present;
# migrate to per-request nonces (django-csp nonce support) to remove it.
CSP_DEFAULT_SRC = ("'self'",)
CSP_SCRIPT_SRC = (
    "'self'", "'unsafe-inline'",
    "https://cdn.tailwindcss.com",
    "https://unpkg.com",
    "https://api.mapbox.com",
    "https://cdn.jsdelivr.net",
)
CSP_STYLE_SRC = (
    "'self'", "'unsafe-inline'",
    "https://fonts.googleapis.com",
    "https://unpkg.com",
    "https://api.mapbox.com",
    "https://cdn.tailwindcss.com",
)
CSP_FONT_SRC = (
    "'self'",
    "https://fonts.gstatic.com",
    "https://fonts.googleapis.com",
)
CSP_IMG_SRC = (
    "'self'", "data:", "blob:",
    "https://api.mapbox.com",
    "https://tile.openstreetmap.org",
    "https://*.basemaps.cartocdn.com",
)
CSP_CONNECT_SRC = (
    "'self'",
    "https://api.mapbox.com",
    "https://events.mapbox.com",
    "https://earthengine.googleapis.com",
    "https://demotiles.maplibre.org",
)
CSP_WORKER_SRC  = ("'self'", "blob:")
CSP_CHILD_SRC   = ("'self'", "blob:")

# CORS Settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Africa/Accra'
USE_I18N = True
USE_TZ = True

# Application Configuration
APP_VERSION = '2.0.0'
APP_NAME = 'SankofaWatch'

# Authentication Settings
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/dashboard/'  # Points to gatekeeper router
LOGOUT_REDIRECT_URL = '/'

# Django REST Framework configuration
REST_FRAMEWORK = {
    # Default: require authentication.  Views that need public access must
    # explicitly set permission_classes = [AllowAny].
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    # Rate limiting — prevents GEE quota exhaustion, brute-force, and audit spam.
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '20/minute',   # unauthenticated callers (very tight)
        'user': '200/minute',  # authenticated users (general API — allows status polling)
        'job_create': '5/minute',  # job creation — burns GEE quota
    },
}

# Email Configuration
# Set EMAIL_USE_CONSOLE=True to print emails to the terminal instead of sending them.
# Set EMAIL_USE_CONSOLE=False (and fill in credentials below) to send real emails.
if config('EMAIL_USE_CONSOLE', default=True, cast=bool):
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST          = config('EMAIL_HOST',          default='smtp.gmail.com')
EMAIL_PORT          = config('EMAIL_PORT',          default=587, cast=int)
EMAIL_USE_TLS       = config('EMAIL_USE_TLS',       default=True, cast=bool)
EMAIL_HOST_USER     = config('EMAIL_HOST_USER',     default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL  = config('DEFAULT_FROM_EMAIL',  default='SankofaWatch <noreply@sankofawatch.ai>')

# ── Celery Configuration ─────────────────────────────────────────────────────
CELERY_BROKER_URL       = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND   = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT   = ['json']
CELERY_TASK_SERIALIZER  = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE         = 'UTC'
CELERY_TASK_TRACK_STARTED = True

# ── Queues ────────────────────────────────────────────────────────────────────
# priority  — all detection jobs (manual + automated tile scans)
# background — timelapse fetching (5-year historical imagery, non-urgent)
from kombu import Queue, Exchange

CELERY_TASK_QUEUES = (
    Queue('priority',   Exchange('priority'),   routing_key='priority'),
    Queue('background', Exchange('background'), routing_key='background'),
)
CELERY_TASK_DEFAULT_QUEUE       = 'priority'
CELERY_TASK_DEFAULT_EXCHANGE    = 'priority'
CELERY_TASK_DEFAULT_ROUTING_KEY = 'priority'

# Enable task priorities 0-9 (higher number = picked first)
CELERY_TASK_QUEUE_MAX_PRIORITY = 10
CELERY_TASK_DEFAULT_PRIORITY   = 5

# Route timelapse fetching to the background queue automatically
CELERY_TASK_ROUTES = {
    'apps.detections.tasks.fetch_site_timelapse': {'queue': 'background'},
}

# Worker: acknowledge tasks only after completion (safer for long pipeline steps)
CELERY_TASK_ACKS_LATE          = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 1  # fetch one task at a time per worker

# ── Beat Schedule ─────────────────────────────────────────────────────────────
from celery.schedules import crontab
CELERY_BEAT_SCHEDULE = {
    'check-assignment-sla-daily': {
        'task': 'apps.core.tasks.check_assignment_sla',
        'schedule': crontab(hour=7, minute=0),
        'options': {'queue': 'priority'},
    },
    'escalate-stale-critical-alerts': {
        'task': 'apps.core.tasks.escalate_stale_alerts',
        'schedule': crontab(minute=0),  # Every hour
        'options': {'queue': 'priority'},
    },
    # Automated Ghana scanner — fires every 5 minutes
    # The task itself checks the 6am–6pm window and skips outside it
    'auto-scan-tick': {
        'task': 'apps.scanning.tasks.auto_scan_tick',
        'schedule': crontab(minute='*/5'),
        'options': {'queue': 'priority'},
    },
    # Daily digest of automated detections — sent at 18:00 (end of scanning window)
    # Manual scan alerts are NOT included; this is automated-only
    'automated-scan-daily-digest': {
        'task': 'apps.scanning.tasks.automated_scan_daily_digest',
        'schedule': crontab(hour=18, minute=0),
        'options': {'queue': 'priority'},
    },
    # Daily concession expiry check — deactivates expired, emails about soon-expiring
    'check-concession-expiry': {
        'task': 'apps.core.tasks.check_concession_expiry',
        'schedule': crontab(hour=9, minute=0),
        'options': {'queue': 'priority'},
    },
}

# Site URL (used for links in notification emails)
SITE_URL = config('SITE_URL', default='http://localhost:8000')

# Ops team email addresses for critical alert escalation
# Override in .env: OPS_EMAILS=ops@example.com,manager@example.com
_ops_raw = config('OPS_EMAILS', default='')
OPS_EMAILS = [e.strip() for e in _ops_raw.split(',') if e.strip()]

# ML Model constants — FPN-ResNet50 v1.0 (HLS optical, Ghana mining belt)
MODEL_BASE_ACCURACY = 0.979        # test-set pixel accuracy; EMA starting point
MODEL_PRECISION_WINDOW = 50        # rolling window for live precision calculation
MODEL_TEST_METRICS = {
    'precision_fallback': 73.1,    # test-set precision (used before any field data)
    'recall': 77.1,
    'f1': 75.0,
    'iou': 60.0,
    'loss': 0.1246,
}

# Map defaults — Ghana mining belt centroid
MAP_DEFAULT_CENTER = [-1.6244, 6.6885]   # [lng, lat]
MAP_DEFAULT_ZOOM = 7

# Inspector workflow thresholds
INSPECTOR_SLA_DAYS = 5                       # days from assignment to SLA deadline
INSPECTOR_MAX_PENDING_ASSIGNMENTS = 10       # max pending before inspector is blocked
ALERT_INCONCLUSIVE_ESCALATION_COUNT = 3     # inconclusives before alert auto-escalates to CRITICAL