# Generated by Django 4.2.28 on 2026-02-19 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-created_at'], 'verbose_name': 'Job', 'verbose_name_plural': 'Jobs'},
        ),
    ]
