# Generated by Django 4.2.28 on 2026-04-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_backfill_job_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='name',
            field=models.CharField(blank=True, default='', help_text='Human-readable name for this job (from uploaded feature name)', max_length=255),
        ),
    ]
