# Generated by Django 4.2.28 on 2026-02-25 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_current_assignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectorassignment',
            name='evidence_photos',
            field=models.JSONField(default=list, help_text='List of media paths for photos taken at the site'),
        ),
        migrations.AddField(
            model_name='inspectorassignment',
            name='outcome',
            field=models.CharField(blank=True, choices=[('mining_confirmed', 'Mining Confirmed'), ('false_positive', 'False Positive'), ('inconclusive', 'Inconclusive')], help_text='Field verification outcome set by inspector after site visit', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='inspectorassignment',
            name='visit_date',
            field=models.DateField(blank=True, help_text='Date the inspector physically visited the site', null=True),
        ),
        migrations.AlterField(
            model_name='inspectorassignment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved')], default='pending', max_length=20),
        ),
    ]
