# Generated by Django 4.2.28 on 2026-03-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_cleanup_old_org_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='alert_min_severity',
            field=models.CharField(choices=[('critical', 'Critical only'), ('high', 'High & Critical'), ('medium', 'Medium, High & Critical'), ('all', 'All alerts')], default='all', help_text='Minimum severity level that triggers an email notification', max_length=10),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='report_default_days',
            field=models.IntegerField(choices=[(7, 'Last 7 days'), (30, 'Last 30 days'), (90, 'Last 90 days')], default=30, help_text='Default date range pre-selected on the report page'),
        ),
    ]
